/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GridPanel: typeof import('./src/components/microComp/GridPanel.vue')['default']
    IconDark: typeof import('./src/components/icons/IconDark.vue')['default']
    IconLight: typeof import('./src/components/icons/IconLight.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    IFluentNumberSymbolSquare24Filled: typeof import('~icons/fluent/number-symbol-square24-filled')['default']
    IIconParkSolidMoreApp: typeof import('~icons/icon-park-solid/more-app')['default']
    IMaterialSymbolsMail: typeof import('~icons/material-symbols/mail')['default']
    IUisSchedule: typeof import('~icons/uis/schedule')['default']
    MicroMail: typeof import('./src/components/MicroMail.vue')['default']
    MicroNumber: typeof import('./src/components/MicroNumber.vue')['default']
    MicroSchedule: typeof import('./src/components/MicroSchedule.vue')['default']
    NoticeBar: typeof import('./src/components/NoticeBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./src/components/microComp/Toolbar.vue')['default']
  }
}
