/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"icon-album" | "icon-all-match" | "icon-battery-charging-30" | "icon-book-4-outline" | "icon-build-circle" | "icon-category-rounded" | "icon-colors-sharp" | "icon-dentistry" | "icon-eos-icons--file-system" | "icon-eos-icons--network-file-system" | "icon-eos-icons--system-group" | "icon-eos-icons--system-ok" | "icon-icon-park-solid--coordinate-system" | "icon-icon-park-solid--system" | "icon-map--post-office" | "icon-material-symbols--settings-system-daydream" | "icon-ri--home-office-fill">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"icon-album" | "icon-all-match" | "icon-battery-charging-30" | "icon-book-4-outline" | "icon-build-circle" | "icon-category-rounded" | "icon-colors-sharp" | "icon-dentistry" | "icon-eos-icons--file-system" | "icon-eos-icons--network-file-system" | "icon-eos-icons--system-group" | "icon-eos-icons--system-ok" | "icon-icon-park-solid--coordinate-system" | "icon-icon-park-solid--system" | "icon-map--post-office" | "icon-material-symbols--settings-system-daydream" | "icon-ri--home-office-fill">;
          default: string;
          required: true;
      };
  }>>, {
      name: "icon-album" | "icon-all-match" | "icon-battery-charging-30" | "icon-book-4-outline" | "icon-build-circle" | "icon-category-rounded" | "icon-colors-sharp" | "icon-dentistry" | "icon-eos-icons--file-system" | "icon-eos-icons--network-file-system" | "icon-eos-icons--system-group" | "icon-eos-icons--system-ok" | "icon-icon-park-solid--coordinate-system" | "icon-icon-park-solid--system" | "icon-map--post-office" | "icon-material-symbols--settings-system-daydream" | "icon-ri--home-office-fill";
  }>;
  export const svgNames: ["icon-album", "icon-all-match", "icon-battery-charging-30", "icon-book-4-outline", "icon-build-circle", "icon-category-rounded", "icon-colors-sharp", "icon-dentistry", "icon-eos-icons--file-system", "icon-eos-icons--network-file-system", "icon-eos-icons--system-group", "icon-eos-icons--system-ok", "icon-icon-park-solid--coordinate-system", "icon-icon-park-solid--system", "icon-map--post-office", "icon-material-symbols--settings-system-daydream", "icon-ri--home-office-fill"];
  export type SvgName = "icon-album" | "icon-all-match" | "icon-battery-charging-30" | "icon-book-4-outline" | "icon-build-circle" | "icon-category-rounded" | "icon-colors-sharp" | "icon-dentistry" | "icon-eos-icons--file-system" | "icon-eos-icons--network-file-system" | "icon-eos-icons--system-group" | "icon-eos-icons--system-ok" | "icon-icon-park-solid--coordinate-system" | "icon-icon-park-solid--system" | "icon-map--post-office" | "icon-material-symbols--settings-system-daydream" | "icon-ri--home-office-fill";
  export default SvgIcon;
}
